homepage/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('polls/', include('polls.urls'))
]

polls/urls.py
from django.urls import path, include
from . import views

app_name = 'polls'
urlpatterns = [
    path('index', views.index, name='index'),
    path('<int:question_id>', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

small_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('polls/', include('polls.urls')),
    path('user_auth/', include('django.contrib.auth.urls')),
    path('user_auth/', include('user_auth.urls')),
]

user_auth/urls.py
from django.urls import path, include
from . import views

app_name = 'user_auth'
urlpatterns = [
    path('', views.user_login, name='login'),
    path('authenticate_user/', views.authenticate_user, name='authenticate_user'),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    """
    Render the home page of the website.

    Args:
        request (HttpRequest): The HTTP request object generated by the client.

    Returns:
        HttpResponse: The rendered HTML template as an HTTP response.

    Raises:
        None

    Example usage:
        >>> request = HttpRequest()
        >>> home(request)
        <HttpResponse object at 0x00000123ABCDEF>
    """
    return render(request, "home.html")

homepage/templates/home.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>Home Page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'homepage_style.css' %}">
  </head>
  <body>
    <nav>
        <ul>
          <li><a href="{% url 'home' %}">Home</a></li>
          <li><a href="{% url 'polls:index' %}">Vote Here</a></li>
          <li><a href="{% url 'user_auth:login' %}">Login</a></li>
        </ul>
    </nav>

    <div class="container">
      <h2>The Futur of</h2>
      <h1>Transportation</h1>
      <p>"Welcome to our survey on now and future transportation options for urban commuting!<br>
        We're excited to hear your opinions on the different layers that make up sustainable transportation options.<br>
        We know that transportation is a crucial part of our daily lives, but it can also have a significant impact on the environment and our wallets.<br>
        By participating in our survey and voting on factors such as environmental impact, affordability, convenience, and safety, you can help<br>
        us identify the most sustainable transportation option for your daily commute.<br>
        Your input will help us create a comprehensive evaluation of the best sustainable transportation option for urban commuting,<br>
        taking into account different aspects and perspectives. Join us in making our cities greener, cleaner, and more affordable by sharing your opinions in our survey!"</p>
    </div>
  </body>
</html>